Improved handling target Lambda from Property, Method, Compile() method.
scottksmith95/LINQKit pull request #126
Opened 2020-10-16 16:20 UTC by sdanyliv

This PR targeted to solve known LINQKit limitations when expression can be expanded only from local variable.
After this fix, these queries are possible.
```cs
var query = from q in query.AsExpandable()
   select new 
    {
        ValueViaMethod = SomeMethod().Invoke(q.Id),
        ValueViaMethodWithparameters = SomeMethodWithParameters(someValue).Invoke(q.Id),
        ValueViaProperty = SomeProperty.Invoke(q.Id)

        // alternative way via Compile

        ValueViaMethodCompile = SomeMethod().Compile()(q.Id),
        ValueViaMethodWithparametersCompile = SomeMethodWithParameters(someValue).Compile()(q.Id),
        ValueViaPropertyCompile = SomeProperty.Compile()(q.Id)
    }
```

2020-10-18 13:10 UTC, StefH requested changes

2020-10-18 13:11 UTC, StefH commented on src/LinqKit.Core/Utilities/ExpressionHelpers.cs
> +            var value = Expression.Lambda(expr).Compile().DynamicInvoke();
you could do a direct return

2020-10-18 13:14 UTC, sdanyliv commented on src/LinqKit.Core/Utilities/ExpressionHelpers.cs
> +                return null;
better to propose change. I din't get what I. have to do

2020-10-19 10:42 UTC, StefH requested changes
I did add some code examples...

2020-10-19 10:44 UTC, sdanyliv commented on src/LinqKit.Core/Utilities/ExpressionHelpers.cs
> +                return null;
Ah, ok. Code style.

2020-10-21 14:21 UTC, k1x1987 commented
This change is very helpful, I'm impatiently waiting for the merge of that.

2020-10-21 16:01 UTC, StefH approved these changes
ok

2020-10-21 16:02 UTC, merged