PredicateBuilder.Create<T>(IEnumerable<T>)
scottksmith95/LINQKit pull request #138
Opened 2021-03-02 20:40 UTC by LucasDiogoDeon

Possibility to create ExpressionStarter<T> instances with Anonymous Types.

Usage:
```csharp
var ienumerable = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, }
    .Select(x => new
    {
        number = x,
        squared = x * x,
    });
var predicate = PredicateBuilder.Create(ienumerable);
predicate = predicate.Or(x => x.number <= 2);
predicate = predicate.Or(x => x.squared >= 64);
```

2021-03-04 19:12 UTC, sdanyliv approved these changes
Nice

2021-03-04 19:27 UTC, StefH requested changes
Please take a look at my comments....

2021-03-04 19:27 UTC, StefH commented on src/LinqKit.Core/PredicateBuilder.cs
> +        public static ExpressionStarter<T> Create<T>(IEnumerable<T> ienumerable, Expression<Func<T, bool>> expr = null)
Would a better name be `New`, just like before?

2021-03-04 19:27 UTC, StefH commented on src/LinqKit.Core/PredicateBuilder.cs
> +        public static ExpressionStarter<T> Create<T>(IEnumerable<T> ienumerable, bool defaultExpression)
Would a better name be `New`, just like before?

2021-03-04 19:27 UTC, StefH commented on tests/LinqKit.Tests.Net452/PredicateBuilderTests.cs
> +            var ienumerable = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, }
You could also use https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?view=net-5.0

2021-03-07 20:25 UTC, LucasDiogoDeon commented
Changed from `Create` to `New`.

2021-03-16 06:51 UTC, StefH approved these changes

2021-03-16 06:51 UTC, merged