Added WithExpressionExpanding configuration extension for EF Core.
scottksmith95/LINQKit pull request #142
Opened 2021-06-11 12:18 UTC by sdanyliv

Well, added extensions which simplifies expanding EF Core queries. For now it is not required to call `AsExpandable()` but just registering with `DbContextOptionsBuilder` `WithExpressionExpanding` extension.
```cs
var builder = new DbContextOptionsBuilder<TestContext>();
builder
    .UseSqlite("DataSource=testdb;mode=memory;cache=shared")
    .WithExpressionExpanding();
```
And then you can create context which queries will be expanded automatically
```cs
var context = new TestContext(builder.Options);
```
This also work with Dependency Injection.

2021-06-11 12:20 UTC, sdanyliv commented on tests/LinqKit.Tests.Net452/PredicateBuilderTests.cs
>          }
Found this bad test and bug in this function.

2021-08-03 16:41 UTC, StefH commented
@sdanyliv 
Can you please solve merge conflict?

2021-08-03 18:59 UTC, sdanyliv commented
Done, I'm glad that you are back ;)

2021-08-03 19:09 UTC, StefH commented
@sdanyliv 
Will this work for all EF versions?

2021-08-03 19:11 UTC, sdanyliv commented
For EF Core 3 and 5, For EF Core 6 should be created new library.

2021-08-03 19:17 UTC, sdanyliv commented
But maybe, it may work with EF Core 6 without any additional manipulations. Not tested.

2021-08-03 19:55 UTC, StefH requested changes

2021-08-03 19:55 UTC, StefH commented on src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableDbContextOptionsBuilderExtensions.cs
> +               ?? new ExpandableDbContextOptionsExtension();
can you place this on previous line?

2021-08-03 19:55 UTC, StefH commented on src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableDbContextOptionsBuilderExtensions.cs
> +                throw new ArgumentNullException(nameof(optionsBuilder));
surround with { and }

This is a general comment for some more code you've added.

2021-08-03 19:55 UTC, StefH commented on src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableDbContextOptionsExtension.cs
> +                        .MakeGenericType(descriptor.ImplementationType),
append this line to previous line

2021-08-03 19:55 UTC, StefH commented on src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableDbContextOptionsExtension.cs
> +                => "LINQKitExpandable";
maybe change this into private const string?

2021-08-03 19:55 UTC, StefH commented on src/LinqKit.Microsoft.EntityFrameworkCore/ExpandableQueryTranslationPreprocessorOptions.cs
> +        public ExpandableQueryTranslationPreprocessorOptions()
do you need an empty constructor?

2021-08-03 19:55 UTC, StefH commented on tests/LinqKit.Microsoft.EntityFrameworkCore31.Tests/LinqKit.Microsoft.EntityFrameworkCore31.Tests.csproj
> +    <Compile Include="..\LinqKit.Microsoft.EntityFrameworkCore.TestsFiltes\**">
`TestsFiltes` ?

2021-08-03 21:19 UTC, sdanyliv commented
Done

2021-08-06 18:02 UTC, StefH approved these changes

2021-08-12 18:28 UTC, merged

2021-09-16 17:56 UTC, rizi commented
@sdanyliv will this work when Include is used?
At the moment when I don't use WithExprrssionExpanding, I have to call Include before AsExpandable?
Br