Use System.Linq.Expressions.ExpressionVisitor where available
scottksmith95/LINQKit pull request #182
Opened 2023-02-26 15:55 UTC by TheConstructor

This also adds support for e.g. Block and Throw expressions, where they are available, making this PR supersede #178.

I tried to build upon the 'expression-visitor'-branch, but found that the visitor-method `VisitMemberAccess` needs to be renamed to `VisitMember` to be able to get a working library. I wish they had chosen `VisitMemberAccess`, as it better communicates what happens, but they didn't.

2023-02-26 16:15 UTC, TheConstructor commented
On first glance this seems to play nice regarding #116 and #118, too. The shipped `ExpressionVisitor`'s `VisitExtension` looks like this:
```cs
protected internal virtual Expression VisitExtension(Expression node) => node.VisitChildren(this);
```
with e.g. `QueryRootExpression` just returning `this`, when receiving this call, but giving the extension-expression the opportunity to interact nicely with the visitor.

2023-03-03 18:39 UTC, StefH commented
@TheConstructor 
Thank you for the PR, I'll need some time to review.

2023-03-18 13:34 UTC, StefH requested changes

2023-03-18 13:34 UTC, StefH commented on src/LinqKit.Core/Utilities/IntrospectionExtensions.cs
> +﻿#if NET35 || NET40 || PORTABLE40 || PORTABLE
Can you please add SILVERLIGHT back?

2023-03-18 13:34 UTC, StefH commented on src/LinqKit.Core/Utilities/IntrospectionExtensions.cs
> +#if NET35 || NET40 || PORTABLE40
Can you please add SILVERLIGHT back?

2023-03-18 13:34 UTC, StefH commented on src/LinqKit.Core/Utilities/TaskHelper.cs
> +#if NET40 || PORTABLE40
Can you please add SILVERLIGHT back?

2023-03-18 15:40 UTC, TheConstructor commented on src/LinqKit.Core/Utilities/IntrospectionExtensions.cs
> +﻿#if NET35 || NET40 || PORTABLE40 || PORTABLE
Done.

2023-03-18 15:40 UTC, TheConstructor commented on src/LinqKit.Core/Utilities/IntrospectionExtensions.cs
> +#if NET35 || NET40 || PORTABLE40
Done.

2023-03-18 15:40 UTC, TheConstructor commented on src/LinqKit.Core/Utilities/TaskHelper.cs
> +#if NET40 || PORTABLE40
Done.

2023-03-18 16:46 UTC, StefH approved these changes

2023-03-18 16:46 UTC, merged

2024-05-27 08:05 UTC, doboczyakos commented
@StefH Why was this approved?
Using the built-in ExpressionVisitor causes calling ReduceAndCheck() inside Expand() which leads to several kind of errors.

Other thing is that the major/minor version of LinqKit.Core should have been increased because the referring packages are broken if they don't use the appropriate version (LinqKit.Microsoft.EntityFrameworkCore 7.1.4 is not compatible with LinqKit.Core 1.2.3).

Please revert this change while you don't the impacts exactly!

One of the errors is:

System.ArgumentException
cannot assign from the reduced node type to the original node type

at System.Linq.Expressions.Expression.ReduceAndCheck()
at System.Linq.Expressions.Expression.VisitChildren(ExpressionVisitor visitor)
at LinqKit.ExpressionReplacer.Visit(Expression exp)
at LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m)
at LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m)
at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
at LinqKit.ExtensionsCore.Expand[TDelegate](Expression`1 expr)

2024-05-27 16:13 UTC, doboczyakos commented
This is a breaking change for custom expressions

2024-05-27 21:02 UTC, TheConstructor commented
@doboczyakos this was merged more than a year ago, there are quite some tests and I used the library during the full time. While it certainly changes things, I would hope, that it is rather for the better (e.g. support for all bundled expression-types).

Can you provide a minimal example, that showcases the problem you encountered? Maybe we can make a new issue of that and find a solution, that works for you, too.

2024-05-28 07:21 UTC, doboczyakos commented
> @doboczyakos this was merged more than a year ago, there are quite some tests and I used the library during the full time. While it certainly changes things, I would hope, that it is rather for the better (e.g. support for all bundled expression-types).
> 
> Can you provide a minimal example, that showcases the problem you encountered? Maybe we can make a new issue of that and find a solution, that works for you, too.

Dear @TheConstructor ,

 I deleted my comment when I found the root cause and a solution, which was the following:
Changing the ExpressionVisitor caused the **change of VisitExtension** from
        protected virtual Expression VisitExtension(Expression extensionExpression)
        {
            return extensionExpression;
        }
 to
        protected internal virtual Expression VisitChildren(ExpressionVisitor visitor)
        {
            if (!CanReduce) throw Error.MustBeReducible();
            return visitor.Visit(ReduceAndCheck());
        }

 When I call Expand() it causes the calling of ReduceAndCheck() which is a **breaking change** and leads to exception in some cases.
I have some tricky custom Expression types. I solved the issue by overriding Accept() in my expression type the following way:
protected override Expression Accept(ExpressionVisitor visitor) => this;

2024-05-28 15:54 UTC, TheConstructor commented
Hey @doboczyakos,

Glad to hear, that you found a way to make it work for you again. I did check how `ExpressionVisitor` changes and pointed it out in https://github.com/scottksmith95/LINQKit/pull/182#issuecomment-1445400032 ; I also checked all the Extension-Expressions I found in EF Core, but I may have missed the [cited default-Implementation in Expression](https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L141). If you write your own extensions, you likely need to override it now. Sorry.

Given that the release is "out there", it may be difficult to change it's version in retrospective, but If you could provide a unit-test, we could be able to prevent similar breaking changes in the future.